# Generated by Django 2.1.4 on 2019-01-14 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Closing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('ammount', models.BigIntegerField(blank=True, null=True)),
                ('total_user', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DirectSponsorIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('level_one', 'level_one'), ('level_two', 'level_two'), ('level_three', 'level_three'), ('level_four', 'level_four'), ('level_five', 'level_five'), ('level_six', 'level_six'), ('level_seven', 'level_seven'), ('level_eight', 'level_eight'), ('level_nine', 'level_nine'), ('level_ten', 'level_ten')], default=None, max_length=25)),
                ('total_users', models.IntegerField(blank=True, null=True)),
                ('remaining', models.BigIntegerField(blank=True, null=True)),
                ('ammount', models.BigIntegerField(blank=True, null=True)),
                ('withdrawl_ammount', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrandTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.BigIntegerField(blank=True, default=0, null=True)),
                ('withdrawn', models.BigIntegerField(blank=True, default=0, null=True)),
                ('remaining', models.BigIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoyaltyIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('level_one', 'level_one'), ('level_two', 'level_two'), ('level_three', 'level_three')], default=None, max_length=25)),
                ('ammount', models.BigIntegerField(blank=True, null=True)),
                ('withdrawl_ammount', models.BigIntegerField(blank=True, null=True)),
                ('remaining', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SingleLegIncome',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='single_leg_profile', serialize=False, to='accounts.Profile')),
                ('level', models.CharField(choices=[('level_one', 'level_one'), ('level_two', 'level_two'), ('level_three', 'level_three'), ('level_four', 'level_four'), ('level_five', 'level_five'), ('level_six', 'level_six'), ('level_seven', 'level_seven'), ('level_eight', 'level_eight'), ('level_nine', 'level_nine'), ('level_ten', 'level_ten'), ('level_eleven', 'level_eleven'), ('level_twelve', 'level_twelve'), ('level_thirteen', 'level_thirteen'), ('level_fourteen', 'level_fourteen'), ('level_fifteen', 'level_fifteen')], default=None, max_length=25)),
                ('date', models.DateField(blank=True, null=True)),
                ('ammount', models.BigIntegerField(blank=True, null=True)),
                ('remaining', models.BigIntegerField(blank=True, null=True)),
                ('upgrade', models.IntegerField(blank=True, null=True)),
                ('withdrawl_ammount', models.BigIntegerField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawlBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, unique=True)),
                ('ammount', models.BigIntegerField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=150, null=True)),
                ('request', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('paid_method', models.CharField(blank=True, max_length=150, null=True)),
                ('paid_by', models.CharField(blank=True, max_length=150, null=True)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('direct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.DirectSponsorIncome')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
                ('royalty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.RoyaltyIncome')),
                ('single_leg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.SingleLegIncome')),
            ],
        ),
        migrations.AddField(
            model_name='singlelegincome',
            name='withdrawl_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawl_bill', to='payments.WithdrawlBill'),
        ),
        migrations.AddField(
            model_name='royaltyincome',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='royalty_profile', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='royaltyincome',
            name='withdrawl_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='royalty_income_withdrawl_bill', to='payments.WithdrawlBill'),
        ),
        migrations.AddField(
            model_name='grandtotal',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='directsponsorincome',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_profile', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='directsponsorincome',
            name='users',
            field=models.ManyToManyField(related_name='level_user', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='directsponsorincome',
            name='withdrawl_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_level_withdrawl_bill', to='payments.WithdrawlBill'),
        ),
    ]
