# Generated by Django 2.1.4 on 2019-01-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('franchise_name', models.CharField(db_index=True, max_length=50)),
                ('franchise_contact_no', models.IntegerField()),
                ('franchise_bank_name', models.CharField(max_length=50)),
                ('franchise_bank_address', models.CharField(max_length=50)),
                ('franchise_bank_ac_no', models.IntegerField()),
                ('franchise_bank_IFSC', models.CharField(max_length=50)),
                ('franchise_profile_image', models.ImageField(upload_to='franchise/franchise_profile_image/%Y/%m/%d')),
                ('pan_card_no', models.CharField(max_length=50)),
                ('aadhar_card_no', models.IntegerField()),
                ('aadhar_card_image', models.ImageField(upload_to='franchise/aadhar_card_image/%Y/%m/%d')),
                ('pan_card_image', models.ImageField(upload_to='franchise/franchise_pan_card_image/%Y/%m/%d')),
                ('pass_book_image', models.ImageField(upload_to='franchise/passbook_image/%Y/%m/%d')),
                ('cancel_cheque', models.ImageField(upload_to='franchise/cancel_cheque_image/%Y/%m/%d')),
                ('bhim_upi', models.IntegerField()),
                ('paypal', models.IntegerField()),
                ('paytm', models.IntegerField()),
                ('phonepay', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Franchise',
                'ordering': ('franchise_name',),
                'verbose_name_plural': 'Franchies',
            },
        ),
    ]
