# Generated by Django 2.1.4 on 2019-01-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise',
            name='aadhar_card_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='bhim_upi',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='franchise_bank_ac_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='franchise_contact_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='paypal',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='paytm',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='phonepay',
            field=models.BigIntegerField(),
        ),
    ]
