# Generated by Django 2.1.4 on 2019-01-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0002_auto_20190116_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise',
            name='aadhar_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='franchise/aadhar_card_image/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='aadhar_card_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='bhim_upi',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='cancel_cheque',
            field=models.ImageField(blank=True, null=True, upload_to='franchise/cancel_cheque_image/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='franchise_bank_IFSC',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='franchise_bank_ac_no',
            field=models.BigIntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='franchise_bank_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='franchise_bank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='franchise_contact_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='franchise_profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='franchise/franchise_profile_image/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='pan_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='franchise/franchise_pan_card_image/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='pan_card_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='pass_book_image',
            field=models.ImageField(blank=True, null=True, upload_to='franchise/passbook_image/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='paypal',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='paytm',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='phonepay',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
