# Generated by Django 2.1.4 on 2019-01-07 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=False)),
                ('activated_date', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=250)),
                ('permanent_address', models.CharField(blank=True, max_length=250)),
                ('user_contact_no', models.BigIntegerField(blank=True, null=True)),
                ('user_bank_name', models.CharField(blank=True, max_length=250)),
                ('user_bank_address', models.CharField(blank=True, max_length=250)),
                ('user_bank_ac_no', models.BigIntegerField(blank=True, null=True)),
                ('user_bank_IFSC', models.CharField(blank=True, max_length=250)),
                ('user_profile_image', models.ImageField(blank=True, upload_to='nhpluser/nhpluser_profile_image')),
                ('pan_card_no', models.CharField(blank=True, max_length=250)),
                ('aadhar_card_no', models.BigIntegerField(blank=True, null=True)),
                ('aadhar_card_image', models.ImageField(blank=True, upload_to='nhpluser/aadhar_card_image')),
                ('pan_card_image', models.ImageField(blank=True, upload_to='nhpluser/user_pan_card_image')),
                ('pass_book_image', models.ImageField(blank=True, upload_to='nhpluser/passbook_image')),
                ('cancel_cheque', models.ImageField(blank=True, upload_to='nhpluser/cancel_cheque_image')),
                ('bhim_upi', models.BigIntegerField(blank=True, null=True)),
                ('paypal', models.BigIntegerField(blank=True, null=True)),
                ('paytm', models.BigIntegerField(blank=True, null=True)),
                ('phonepay', models.BigIntegerField(blank=True, null=True)),
                ('sponsored_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
