# Generated by Django 2.1.4 on 2019-01-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sponsored_user',
            field=models.ManyToManyField(to='accounts.Profile'),
        ),
    ]
