# Generated by Django 2.1.4 on 2019-01-08 15:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190108_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sponsored_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
