# Generated by Django 2.1.4 on 2019-01-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190108_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sponsored_user',
            field=models.ManyToManyField(to='accounts.Profile'),
        ),
    ]
