# Generated by Django 2.1.4 on 2019-01-09 08:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190109_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sponsored_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
