# Generated by Django 2.1.4 on 2019-01-13 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_auto_20190109_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='refered_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refered_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sponsored_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='sponsored_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
