# Generated by Django 2.1.4 on 2019-01-14 04:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190113_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sponsored_user',
            field=models.ManyToManyField(related_name='sponsored_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
