# Generated by Django 2.1.4 on 2019-01-14 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190114_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sponsored_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='sponsored_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
