# Generated by Django 2.1.4 on 2019-01-23 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190116_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='googlepay',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sponsored_user',
            field=models.ManyToManyField(related_name='sponsored_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
