# Generated by Django 2.1.4 on 2019-01-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='Gallery/%Y/%m/%d')),
                ('image_title', models.CharField(max_length=100)),
                ('image_uploaded_by', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('term', models.TextField()),
            ],
            options={
                'verbose_name': 'Term',
                'ordering': ('title',),
                'verbose_name_plural': 'Terms',
            },
        ),
    ]
