# Generated by Django 2.1.4 on 2019-01-14 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Epin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=200, unique=True)),
                ('pin_value', models.IntegerField()),
                ('pin_name', models.CharField(blank=True, max_length=50, null=True)),
                ('used', models.BooleanField(blank=True, default=False, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('sold_to', models.CharField(blank=True, max_length=250, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('used_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
